{% set name = "qassfilt" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hsamrach/QAssfilt/archive/refs/tags/{{ version }}.tar.gz
  sha256: bfbdcc4782d748a0b626b88b2d81bd5beaf41e4f0359e2c5c3839030763b27c5

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage("qassfilt", max_pin="x") }}
  script: |
    mkdir -p "${PREFIX}/bin"
    cp qassfilt.sh "${PREFIX}/bin/qassfilt"
    chmod +x "${PREFIX}/bin/qassfilt"

requirements:
  host:
    - bash
  run:
    - bash

about:
  home: https://github.com/hsamrach/QAssfilt
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "QAssfilt: a decision-making initiator in genome assembly filtering"
  description: |
    Make sure that the following tools are installed in the environment:
      - fastp
      - spades
      - seqkit
      - checkm2
      - quast
      - kraken2
      - gtdbtk
      - abritamr
      - abricate
      - multiqc
      Otherwise, run qassfilt -ini
test:
  commands:
    - qassfilt --help

extra:
  identifiers:
    - biotools:qassfilt
  requirements_note: |
        Conda and mamba must be installed before running QAssfilt.
