{% set name = "qassfilt" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hsamrach/QAssfilt/archive/refs/tags/{{ version }}.tar.gz
  sha256: d2027a73553106796d50ce1d0d0f1b00d609ff6ffe1c94f8905647a6e6bb88f1

build:
  noarch: generic
  number: 1
  script: |
    mkdir -p "${PREFIX}/bin"
    cp qassfilt.sh "${PREFIX}/bin/qassfilt"
    chmod +x "${PREFIX}/bin/qassfilt"

requirements:
  host:
    - bash
  run:
    - bash

about:
  home: https://github.com/hsamrach/QAssfilt
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "QAssfilt: a ready-to-use genome assembly quality filtering pipeline"
  description: |
    Make sure that the following tools are installed in the environment:
      - fastp
      - spades
      - seqkit
      - checkm2
      - quast
      - kraken2
      - gtdbtk
      - abritamr
      - abricate
      - multiqc
      Otherwise, run qassfilt -ini
test:
  commands:
    - qassfilt --help

extra:
  identifiers:
    - biotools:qassfilt
  requirements_note: |
    The following external tools are required but not installed automatically:
      fastp, spades, seqkit, checkm2, quast, kraken2,
      gtdbtk, abritamr, abricate, multiqc
